name: Deploy Backend to Somee

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"   # Chỉ chạy khi backend thay đổi

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.BE_FTP_HOST }}
          username: ${{ secrets.BE_FTP_USER }}
          password: ${{ secrets.BE_FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: /www.yourbackend.somee.com/   # Thay thư mục hosting backend của bạn
          protocol: ftp
